PracticaExamenAWS/Models/ErrorViewModel.cs
namespace PracticaExamenAWS.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PracticaExamenAWS/Models/Serie.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PracticaExamenAWS.Models
{
    [Table("SERIES")]
    public class Serie
    {
        [Key]
        [Column("IDSERIE")]
        public int IdSerie { get; set; }

        [Column("SERIE")]
        public string Nombre { get; set; }

        [Column("IMAGEN")]
        public string Imagen { get; set; }

        [Column("ANYO")]
        public int Anio { get; set; }
    }
}

PracticaExamenAWS/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using PracticaExamenAWS.Models;

namespace PracticaExamenAWS.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PracticaExamenAWS/Controllers/SeriesController.cs
using Microsoft.AspNetCore.Mvc;
using PracticaExamenAWS.Models;
using PracticaExamenAWS.Repositories;
using PracticaExamenAWS.Services;

namespace PracticaExamenAWS.Controllers
{
    public class SeriesController : Controller
    {
        private RepositorySeries repository;
        private ServiceBucketS3 service;
        public SeriesController(RepositorySeries repo, ServiceBucketS3 ser)
        {
            this.repository = repo;
            this.service = ser;
        }

        public async Task<IActionResult> Index()
        {
            return View(await this.repository.GetSeriesAsync());
        }

        public async Task<IActionResult> Details(int id)
        {
            return View(await this.repository.FindSerieByIdAsync(id));
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Serie serie, IFormFile file)
        {
            using (Stream stream = file.OpenReadStream())
            {
                await this.service.UploadFileAsync(file.FileName, stream);
            }
            serie.Imagen = file.FileName;
            await this.repository.CreateSerieAsync(serie);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Update(int id)
        {
            return View(await this.repository.FindSerieByIdAsync(id));
        }

        [HttpPost]
        public async Task<IActionResult> Update(Serie serie)
        {
            await this.repository.UpdateSerieAsync(serie);
            return RedirectToAction("Index");
        }


        public async Task<IActionResult> Delete(int id)
        {
            await this.repository.DeleteSerie(id);
            return RedirectToAction("Index");
        }
    }
}

PracticaExamenAWS/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

PracticaExamenAWS/Views/Series/Create.cshtml
@model PracticaExamenAWS.Models.Serie

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Serie</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="IdSerie" class="control-label"></label>
                <input asp-for="IdSerie" class="form-control" />
                <span asp-validation-for="IdSerie" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Imagen" class="control-label"></label>
                <input type="file" name="file" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Anio" class="control-label"></label>
                <input asp-for="Anio" class="form-control" />
                <span asp-validation-for="Anio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PracticaExamenAWS/Views/Series/Details.cshtml
@model PracticaExamenAWS.Models.Serie

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Serie</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdSerie)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdSerie)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Imagen)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Imagen)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Anio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Anio)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

PracticaExamenAWS/Views/Series/Index.cshtml
@model IEnumerable<PracticaExamenAWS.Models.Serie>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create" asp-controller="Series">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdSerie)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Imagen)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Anio)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IdSerie)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Imagen)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Anio)
            </td>
            <td>
                    <a asp-action="Details" asp-controller="Series" asp-route-id="@item.IdSerie" class="btn btn-info">Details</a>
                    <a asp-action="Delete" asp-controller="Series" asp-route-id="@item.IdSerie" class="btn btn-danger">Delete</a>
                    <a asp-action="Update" asp-controller="Series" asp-route-id="@item.IdSerie" class="btn btn-warning">Update</a>
                
            </td>
        </tr>
}
    </tbody>
</table>

PracticaExamenAWS/Views/Series/Update.cshtml
@model PracticaExamenAWS.Models.Serie

@{
    ViewData["Title"] = "Update";
}

<h1>Update</h1>

<h4>Serie</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Update">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="IdSerie" class="control-label"></label>
                <input asp-for="IdSerie" class="form-control" />
                <span asp-validation-for="IdSerie" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Imagen" class="control-label"></label>
                <input asp-for="Imagen" class="form-control" />
                <span asp-validation-for="Imagen" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Anio" class="control-label"></label>
                <input asp-for="Anio" class="form-control" />
                <span asp-validation-for="Anio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PracticaExamenAWS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PracticaExamenAWS</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PracticaExamenAWS.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PracticaExamenAWS</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Series" asp-action="Index">Series</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - PracticaExamenAWS - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>